modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="nuclear_mod"
version="1.0.0"
displayName="nuclear mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jerimiah, MCreator"

[[dependencies.nuclear_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




